### Get all persons
POST http://localhost:8080/persons/bulk
Content-Type: application/json
Accept: application/json

{
  "method": "DEFAULT"
}

### getAll 스트림 병렬 처리
POST http://localhost:8080/persons/bulk
Content-Type: application/json
Accept: application/json

{
  "method": "STREAM"
}

### getAll list 처리
POST http://localhost:8080/persons/bulk
Content-Type: application/json
Accept: application/json

{
  "method": "NON_STREAM"
}


### Get persons by IDs
POST http://localhost:8080/persons/bulk/ids
Content-Type: application/json
Accept: application/json

{
  "method": "DEFAULT",
  "ids": [1, 2, 3, 4, 5]
}

### Get persons by IDs
POST http://localhost:8080/persons/bulk/ids
Content-Type: application/json
Accept: application/json

{
  "method": "CHUNK",
  "ids": [1, 2, 3, 4, 5]
}

### Get persons by IDs
POST http://localhost:8080/persons/bulk/ids
Content-Type: application/json
Accept: application/json

{
  "method": "PROJECTION",
  "ids": [6, 7, 8, 9, 10]
}

### Get persons by IDs
POST http://localhost:8080/persons/bulk/ids
Content-Type: application/json
Accept: application/json

{
  "method": "TEMP_TABLE_JOIN",
  "ids": [6, 7, 8, 9, 10]
}
